# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-09 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_1', models.IntegerField(default=0, verbose_name='最低值')),
                ('max_1', models.IntegerField(default=0, verbose_name='最高值')),
                ('min_2', models.IntegerField(default=0, verbose_name='最低值')),
                ('max_2', models.IntegerField(default=0, verbose_name='最高值')),
                ('min_3', models.IntegerField(default=0, verbose_name='最低值')),
                ('max_3', models.IntegerField(default=0, verbose_name='最高值')),
                ('min_4', models.IntegerField(default=0, verbose_name='最低值')),
                ('max_4', models.IntegerField(default=0, verbose_name='最高值')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目')),
            ],
            options={
                'verbose_name': '默认价格区间',
                'verbose_name_plural': '默认价格区间',
            },
        ),
    ]
