# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-09 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_pricerange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricerange',
            old_name='max_1',
            new_name='max',
        ),
        migrations.RenameField(
            model_name='pricerange',
            old_name='min_1',
            new_name='min',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='max_2',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='max_3',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='max_4',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='min_2',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='min_3',
        ),
        migrations.RemoveField(
            model_name='pricerange',
            name='min_4',
        ),
    ]
