# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181209_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品'),
        ),
    ]
