# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20181208_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavingmessage',
            name='subject',
            field=models.CharField(default='', help_text='留言主题', max_length=100, verbose_name='主题'),
        ),
    ]
